---
- hosts: kube_master, kube_node
  serial: 1
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: create the new user
      ansible.builtin.user:
        name: "{{ new_user }}"
        state: present
        password: "!"
        shell: /bin/bash
        groups: "sudo"
        append: yes
        create_home: yes

    - name: Configure passwordless sudo for the new user
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/{{ new_user }}
        create: true
        mode: '0440'
        line: '{{ new_user }} ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'

    - name: Ensure .ssh directory exists with correct permissions
      ansible.builtin.file:
        path: "/home/{{ new_user }}/.ssh"
        state: directory
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        mode: "0700"

    - name: Create authorized_keys file
      ansible.builtin.lineinfile:
        path: "/home/{{ new_user }}/.ssh/authorized_keys"
        line: "{{ ssh_public_key }}"
        create: yes  # Ensure the file is created if it doesn't exist
        mode: '0600'
        owner: "{{ new_user }}"
        group: "{{ new_user }}"
        regexp: "^{{ ssh_public_key }}"

    #- name: Add public key to authorized_keys
    #  ansible.posix.authorized_key:
    #    user: "{{ new_user }}" # Or specify the target user
    #    state: present
    #    key: "{{ ssh_public_key }}"