---
- hosts: kube_master, kube_node
  serial: 1
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Generate and save kubeadm join command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: kube_join_command
      when: inventory_hostname in groups['kube_master']

    - name: Debug join output
      ansible.builtin.debug:
        var: kube_join_command

    - name: Execute join with generated command from kube_master
      ansible.builtin.shell: "{{ hostvars[groups['kube_master'] | last].kube_join_command }}"
      when: inventory_hostname in groups['kube_node']