---
- hosts: kube_master
  serial: 1
  remote_user: "{{ rmt_usr }}"
  #become_user: "{{ rmt_usr }}"
  #become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Print the ansible_user
      become: yes
      debug:
        msg: "The Ansible connection user is: {{ ansible_user }}"
    - name: Debug ansible env
      become: yes
      ansible.builtin.debug:
        var: ansible_env