---
- hosts: kube_master
  serial: 1
  remote_user: "{{ rmt_usr }}"
  #become_user: "{{ rmt_usr }}"
  # become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    # - name: Print the ansible_user
      # become: yes
      # debug:
        # msg: "The Ansible connection user is: {{ ansible_user }}"
    # - name: Debug ansible env
      # become: yes
      # ansible.builtin.debug:
        # var: ansible_env
    - name: Setup Tigera operator for Calico CNI
      ansible.builtin.shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/tigera-operator.yaml
      register: tigera_output
      when: inventory_hostname in groups['kube_master']

    - name: Debug tigera output
      ansible.builtin.debug:
        var: tigera_output
      when: inventory_hostname in groups['kube_master']

    - name: Pause for 30 seconds for Tigera operator setup
      ansible.builtin.pause:
        seconds: 30

    - name: Setup Calico CNI
      ansible.builtin.shell: kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.30.3/manifests/custom-resources.yaml
      register: calico_output
      when: inventory_hostname in groups['kube_master']

    - name: Debug calico output
      ansible.builtin.debug:
        var: calico_output

    # - name: Generate and save kubeadm join command
    #   become: yes
    #   ansible.builtin.shell: kubeadm token create --print-join-command
    #   register: kube_join_output
    #   when: inventory_hostname in groups['kube_master']
    #   run_once: true

    # - name: Debug join output
    #   ansible.builtin.debug:
    #     var: kube_join_output
    #   when: inventory_hostname in groups['kube_master']

    # - name: Set kubeadm_join_command fact for worker nodes
    #   ansible.builtin.set_fact: 
    #     kube_join_command: "{{ hostvars['master']['kube_join_output'].stdout }}"
    #   when: inventory_hostname in groups['kube_node']

    # - name: Debug join command
    #   ansible.builtin.debug:
    #     var: kube_join_command
    #   when: inventory_hostname in groups['kube_node']

    # - name: Run join command
    #   ansible.builtin.shell: "{{ kube_join_command }}"
    #   when: inventory_hostname in groups['kube_node']