name: Create k8s user with no password sudo rights

on: 
  workflow_dispatch:
  workflow_call:

jobs:
  init:
    name: Create ubuntu user
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Get inventory file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TF_BUCKET_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_BUCKET_SECRET }}
          AWS_REGION: ${{ secrets.TF_BUCKET_REGION }}
        run: |
          mkdir ./ansible/inventory
          aws s3api get-object --bucket ${{ secrets.TF_BUCKET_NAME }} --endpoint ${{ secrets.TF_BUCKET_REGION_ENDPOINT_URL}}  --key inventory.yaml ./ansible/inventory/inventory.yaml
          
        # aws s3 cp s3://${{ secrets.TF_BUCKET_NAME }}/inventory.yaml ./inventory.yaml

      - name: Test list file
        run: ls -al

      - name: Test show file content
        run: cat ./ansible/inventory/inventory.yaml

      #- name: Set up Python
      #  uses: actions/setup-python@v5
      #  with:
      #    python-version: '3.x'

      #- name: Install Ansible
      #  run: pip install ansible

      - name: Install Ansible
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y --update ppa:ansible/ansible
          sudo apt install -y ansible

      - name: Run Ansible create user playbook
        env:
          ANSIBLE_USER: ${{ secrets.ANSIBLE_USER }}
          ANSIBLE_HOST_KEY_CHECKING: 'false' # Disable host key checking for CI/CD
          ANSIBLE_BECOME_PASS: '' # Provide empty password for passwordless sudo
        run: ansible-playbook -i ./ansible/inventory/inventory.yaml ./ansible/playbooks/createUser.yaml --extra-vars "new_user=${{ secrets.KUBE_USER}}" --extra-vars "ssh_public_key='${{ secrets.SSH_PUBLIC_KEY }}'"

      - name: Run Ansible create cluster playbook
        env:
          ANSIBLE_USER: ${{ secrets.KUBE_USER}}
          ANSIBLE_HOST_KEY_CHECKING: 'false' # Disable host key checking for CI/CD
          ANSIBLE_BECOME_PASS: '' # Provide empty password for passwordless sudo
        run: ansible-playbook -i ./ansible/inventory/inventory.yaml ./ansible/playbooks/createCluster.yaml 